name: LaunchServer
description: "KeeperJerry's NekroLaunchServer"
version: 1.0

author: "KeeperJerry & sashok724 LLC"
website: 'https://launcher-sashok724.keeperjerry.ru/'

main: launchserver.plugin.bukkit.LaunchServerPluginBukkit

commands:
  launchserver:
    aliases: [launcher,ls,l]
    description: "Primary LaunchServer command"
    usage: '/<command> <action> [args...]'
